APS_Project2/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('queries/', include('queries.urls')),
    path('events/', include('events.urls')),
]

accounts/urls.py
from django.urls import path

from APS_Project2 import settings
from . import views
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('special/', views.special, name='special'),
    path('profile/', views.profile, name='profile'),
    path('userslist/', views.userslist, name='userslist'),
    path('viewprofile/<str:pk>/', views.viewprofile, name='viewprofile')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

blogs/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('writeblogs/', views.writeblogs, name='writeblogs'),
    path('editblogs/<str:pk>/', views.editblogs, name='editblogs'),
    path('deleteblogs/<str:pk>/', views.deleteblogs, name='deleteblogs'),
    path('readblogs/<str:pk>/', views.readblogs, name='readblogs'),
]

events/urls.py
from django.urls import path

from APS_Project2 import settings
from . import views
from django.conf.urls.static import static

app_name = 'events'

urlpatterns = [
    path('', views.events, name='events'),
    path('uploadevent/', views.uploadevent, name='uploadevent'),
    # path('deletepost/<str:pk>/', views.deletepost, name='deletepost'),
    # path('editpost/<str:pk>/', views.editpost, name='editpost'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

posts/urls.py
from django.urls import path

from APS_Project2 import settings
from . import views
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('uploadpost/', views.uploadpost, name='uploadpost'),
    path('deletepost/<str:pk>/', views.deletepost, name='deletepost'),
    path('editpost/<str:pk>/', views.editpost, name='editpost'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

blogs/models.py
from django.db import models
from accounts.models import UserProfileInfo
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class blogs(models.Model):
    blogtopic = models.CharField(max_length = 200)
    blogcontent = models.CharField(max_length = 3000)
    

    user = models.ForeignKey(User, on_delete = models.CASCADE, default = 1) 
    author = models.CharField(max_length = 100, default = "")
    tag = models.CharField(max_length = 100, default = "")
    
    def __str__(self):
        return self.blogtopic   

class blogcomments(models.Model):
    blog = models.ForeignKey(blogs, related_name = "comments", on_delete = models.CASCADE)
    commentauthor = models.CharField(max_length = 200)
    commentcontent = models.CharField(max_length = 3000)

    def __str__(self):
        return '%s - %s' %(self.blog.blogtopic, self.commentauthor)

events/models.py
from django.db import models

# Create your models here.

class events(models.Model):
    eventTopic = models.CharField(max_length=300, default="")
    eventDesc = models.CharField(max_length=3000, default="")
    eventImg = models.ImageField(upload_to = 'event_pics', blank = True)
    eventDate = models.CharField(max_length=50, default="")
    eventOrganizer = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.eventTopic

posts/models.py
from django.db import models

# Create your models here.

class posts(models.Model):
    postimage = models.ImageField(upload_to = 'posts_pics', blank = True)
    caption = models.CharField(max_length=1000, default="")
    author = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.author

class postcomments(models.Model):
    post = models.ForeignKey(posts, related_name = "comments", on_delete = models.CASCADE)
    commentauthor = models.CharField(max_length = 200)
    commentcontent = models.CharField(max_length = 3000)

    def __str__(self):
        return self.commentauthor

blogs/forms.py
from dataclasses import field
from django.forms import ModelForm
from django import forms
from . models import blogs, blogcomments

TAG_CHOICES = [
    ('Artificial_Intelligence', 'Artificial_Intelligence'),
    ('Machine_Learning', 'Machine_Learning'),
    ('Robotics', 'Robotics'),
    ('Internet_of_Things', 'Internet_of_Things'),
    ('Web_Development', 'Web_Development'),
    ('App_Development', 'App_Development'),
    ('Competitive_Programming', 'Competitive_Programming'),
]

class writeblogform(ModelForm):
    blogtopic = forms.CharField(widget=forms.Textarea(attrs={'rows':1,'class': 'input-fields', 'placeholder': 'Enter the topic of your blog here'}))
    blogcontent = forms.CharField(widget=forms.Textarea(attrs={'rows':8, 'cols':120, 'class': 'input-fields', 'placeholder': 'Enter the blog content here'})) 
    tag = forms.CharField(label='Tag', widget=forms.Select(choices=TAG_CHOICES,attrs={'class': 'input-fields'}))

    class Meta:
        model = blogs
        fields = ['blogtopic', 'blogcontent', 'tag']

class blogcommentsform(ModelForm):
    commentcontent = forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'cols':60, 'class': 'input-fields', 'placeholder': 'Enter your comment here'}))

    class Meta:
        model = blogcomments
        fields = ['commentcontent']

events/forms.py
from django import forms
from .models import events

class eventsForm(forms.ModelForm):

    class Meta():
        model = events
        fields = ('eventTopic', 'eventDesc', 'eventImg', 'eventDate', 'eventOrganizer')

posts/forms.py
from django import forms
from .models import posts

class postsForm(forms.ModelForm):

    class Meta():
        model = posts
        fields = ('postimage', 'caption',)

blogs/views.py
from re import search
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . forms import writeblogform, TAG_CHOICES, blogcommentsform
from . models import blogs as blogsmodels, blogcomments as blogcommentsmodels
from accounts.models import UserProfileInfo

# Create your views here.

def blogs(request):
    contents = blogsmodels.objects.all()
    user = request.user
    taglist = []
    for i in TAG_CHOICES:
        taglist.append(i[0])
    search_input = request.GET.get('search-area') or ''
    tag_input = request.GET.get('filter_tags') or ''
    if tag_input and tag_input != 'All':
        contents = contents.filter(tag__icontains = tag_input)
    if search_input:
        contents = contents.filter(blogtopic__istartswith = search_input)
    return render(request, 'blogs.html', {'contents' : contents, 'user' : user, 'search_input' : search_input, 'taglist' : taglist, 'tag_input' : tag_input})

def writeblogs(request):
    if request.POST:
        form = writeblogform(request.POST)
        if form.is_valid():
            fs = form.save(commit=False)
            fs.author = request.user
            fs.save()
        return redirect(blogs)
    else:
        form = writeblogform()
    return render(request, 'writeblogs.html', {'form' : form}) 

def editblogs(request, pk):
    blog = blogsmodels.objects.get(id = pk)
    
    if request.POST:
        form = writeblogform(request.POST, instance = blog)
        if form.is_valid():
            form.save()
        return redirect('../../../accounts/profile')
    else:
        form = writeblogform(instance = blog)

    return render(request, 'writeblogs.html', {'form' : form})

def deleteblogs(request, pk):
    blog = blogsmodels.objects.get(id = pk)
    
    if request.POST:
        blog.delete()
        return redirect('../../../accounts/profile')

    return render(request, 'deleteblogs.html', {'blog' : blog})

def readblogs(request, pk):
    blog = blogsmodels.objects.get(id = pk)
    if request.POST:
        form = blogcommentsform(request.POST)
        if form.is_valid():
            fs = form.save(commit=False)
            fs.commentauthor = request.user
            fs.blog = blog
            fs.save()
        return redirect(blogs)
    else:
        form = blogcommentsform()
    return render(request, 'readblogs.html', {'content' : blog, 'form' : form})

events/views.py
from django.shortcuts import render
from .forms import eventsForm
from . models import events as eventsModels
 
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from APS_Project2 import settings

def events(request):
    contents = eventsModels.objects.all()
    user = request.user

    return render(request, 'events.html', {'contents' : contents, 'user' : user,})

def uploadevent(request):

    if request.method == 'POST':
        form = eventsForm(data=request.POST)

        if form.is_valid():
            fs = form.save(commit=False)
            fs.author = request.user

            if 'eventImg' in request.FILES:
                fs.eventImg = request.FILES['eventImg']

            fs.save()
            return HttpResponseRedirect(reverse('events:events'))
        else:
            print(form.errors)
    else:
        form = eventsForm()
        
    return render(request, 'uploadevent.html', {'form':form})

# def editpost(request, pk):
#     post = postsModels.objects.get(id = pk)
    
#     if request.POST:
#         form = postsForm(request.POST, instance = post)
#         if form.is_valid():
#             form.save()
#         return HttpResponseRedirect(reverse('accounts:profile'))
#     else:
#         form = postsForm(instance = post)

#     return render(request, 'uploadpost.html', {'form' : form})

# def deletepost(request, pk):
#     post = postsModels.objects.get(id = pk)
    
#     if request.POST:
#         post.delete()
#         return HttpResponseRedirect(reverse('accounts:profile'))

#     return render(request, 'deleteposts.html', {'post' : post})

posts/views.py
from django.shortcuts import render
from .forms import postsForm
from . models import posts as postsModels
 
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from APS_Project2 import settings

def posts(request):
    contents = postsModels.objects.all()
    user = request.user

    return render(request, 'posts.html', {'contents' : contents, 'user' : user,})

def uploadpost(request):

    if request.method == 'POST':
        form = postsForm(data=request.POST)

        if form.is_valid():
            fs = form.save(commit=False)
            fs.author = request.user

            if 'postimage' in request.FILES:
                fs.postimage = request.FILES['postimage']

            fs.save()
            return HttpResponseRedirect(reverse('posts:posts'))
        else:
            print(form.errors)
    else:
        form = postsForm()
        
    return render(request, 'uploadpost.html', {'form':form})

def editpost(request, pk):
    post = postsModels.objects.get(id = pk)
    
    if request.POST:
        form = postsForm(request.POST, instance = post)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('accounts:profile'))
    else:
        form = postsForm(instance = post)

    return render(request, 'uploadpost.html', {'form' : form})

def deletepost(request, pk):
    post = postsModels.objects.get(id = pk)
    
    if request.POST:
        post.delete()
        return HttpResponseRedirect(reverse('accounts:profile'))

    return render(request, 'deleteposts.html', {'post' : post})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'master.css' %}">
    {% block link %}
    {% endblock %}
    <title>Document</title>
</head>
<body style="background: url('{% static "./ssn1.jpg" %}') 50% 0 no-repeat fixed;">
    <nav id="navbar" class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
            <h2 class="navbar-brand">SSN APS</h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                    {% if user.is_superuser %}
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        {% if not user.is_superuser %}
                            <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                        {% endif %}
                        <a class="nav-link" href="{% url 'events:events' %}">Events</a>
                        <a class="nav-link" href="{% url 'blogs' %}">Blogs</a>
                        <a class="nav-link" href="{% url 'posts:posts' %}">Posts</a>
                        <a class="nav-link" href="{% url 'queries' %}" >Queries</a>
                        <a class="nav-link" href="{% url 'accounts:userslist' %}">Users</a>
                        <a class="nav-link" href="{% url 'accounts:user_logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        <a class="nav-link" href="{% url 'accounts:user_login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="content-container">
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>

templates/blogs.html
{% extends "base.html" %}

{% block content %}
    <!-- <div class="head-container">
        <h1>Welocome to Blogs Page</h1>        
    </div> -->

    <form method="GET" class="forms">
        <input type="text" name="search-area" value="{{ search_input }}" class="input-fields"> 
        <button type="submit" class="action-buttons search">Search</button>
    </form>

    <form method="GET" class="forms">
        <select name="filter_tags" id="filter_tags" class="input-fields">
            {% if tag_input %}
                <option value="{{ tag_input }}">{{ tag_input }}</option>
            {% endif %}
            <option value="">All</option>
            {% for tag in taglist %}
                <option value="{{ tag }}">{{ tag }}</option>
            {% endfor %}
        </select>
        <button class="action-buttons filter" type="submit">Filter</button>
    </form>
    <button class="action-buttons addquery"><a href="./writeblogs">Write New Blog</a></button>
    <br>
    <div class="post-container">
        {% for content in contents reversed %}
        {% if content.author != user.username %}
        <div class="data-card bk w50">
            <h3><a href="{% url 'readblogs' content.id %}">{{ content.blogtopic }}</a></h3>
            <p><b>@{{ content.author }}</b></p>
            <p>#{{ content.tag }}</p>
        </div>
            
        {% endif %}
            <!-- {% if content.author == user.username %}
            <button><a href="{% url 'editblogs' content.id %}">Edit Blog</a></button>
            <button><a href="{% url 'deleteblogs' content.id %}">Delete Blog</a></button>
        {% endif %} -->

    {% endfor %}
    </div>
    
{% endblock %}

templates/deleteblogs.html
{% extends "base.html" %}

{% block content %}
<div class="head-container">
    <h3>Are you sure you want delete "{{blog}}" ?</h3>
    <form action="{% url 'deleteblogs' blog.id %}" method="POST">
        {% csrf_token %}
        <button class="action-buttons cancel"><a href="{% url 'accounts:profile' %}">Cancel</a></button>
        <button type="submit" class="action-buttons delete">Delete</button>
    </form>
</div>

{% endblock %}

templates/deletequery.html
{% extends "base.html" %}

{% block content %}
<div class="head-container">
    <h3>Are you sure you want delete "{{ query }}" ?</h3>
    <form action="{% url 'deletequery' query.id %}" method="POST">
        {% csrf_token %}
        <button class="action-buttons cancel"><a href="{% url 'accounts:profile' %}">Cancel</a></button>
        <button class="action-buttons delete" type="submit">Delete</button>
    </form>
</div>    
    
{% endblock %}

templates/events.html
{% extends "base.html" %}

{% block content %}
<!-- <div class="text-container">
        <h1 class="welcome-text">
            Welcome to SSN Alumni Portal System
            <p style="font-size: 1rem;margin-top: 2rem;" align="justify">
                Students find it difficult to connect with their Alumni. This project aims at creating a website for students to connect with their alumni in the college and gain knowledge related to their domain. The project will also help the alumni to find out their future prospects in the domain. The website would be interactive as it will have a discussion forum and database for the alumni. It will serve as a link between present students and their Alumini, who are working professionals in different domains of life. This will motivate the students to achieve higher goals in life. By doing this project I wish to contribute my bit towards the betterment of the society.

                As technology is playing an important role in
            </p>
        </h1>
    </div> -->
<!-- Google font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Titillium+Web:400,400i,600,600i,700,700i,900">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i,800,800i">
<!-- Bootstrap -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<!-- icofont -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionic/1.3.2/css/ionic.css">
<!-- carousel -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">


<section class="blog_section">
    <div class="container">
        <div class="blog_content">
            <div class="owl-carousel owl-theme">
                {% for content in contents reversed %}
                <div class="blog_item">
                    <div class="blog_image">
                        <img class="img-fluid" src="./media/{{ content.eventImg }}" alt="images not found">
                        <span><i class="icon ion-md-create"></i></span>
                    </div>
                    <div class="blog_details">
                        <div class="blog_title">
                            <h5>{{ content.eventTopic }}</h5>
                        </div>
                        <ul>
                            <li><i class="icon ion-md-person"></i>{{ content.eventOrganizer }}</li>
                            <li><i class="icon ion-md-calendar"></i>{{ content.eventDate }}</li>
                        </ul>
                        <p>{{ content.eventDesc }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- <button class="action-buttons addquery" style="margin: 3rem;"><a href="./uploadevent">New Event</a></button> -->
        <div class="post-container" style="margin: 2rem;">
        </div>
</section>

</div>


<!-- Jquery -->
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<!-- bootstrap -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<!-- carousel -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js"></script>
<script src="../static/app.js"></script>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="text-container">
        <h1 class="welcome-text">
            Welcome to SSN Alumni Portal System
            <p style="font-size: 1rem;margin-top: 2rem;" align="justify">
                Students find it difficult to connect with their Alumni. This project aims at creating a website for students to connect with their alumni in the college and gain knowledge related to their domain. The project will also help the alumni to find out their future prospects in the domain. The website would be interactive as it will have a discussion forum and database for the alumni. It will serve as a link between present students and their Alumini, who are working professionals in different domains of life. This will motivate the students to achieve higher goals in life. By doing this project I wish to contribute my bit towards the betterment of the society.

                As technology is playing an important role in
            </p>
        </h1>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="login-container">
    <h1>Login Please</h1>

    <form action="{% url 'accounts:user_login' %}" method="POST">
        {% csrf_token %}
        <div class="mar">
            <input type="text" name="username" placeholder="Enter your Username" class="input-fields">
        </div>

        <div class="mar">
            <input type="password" name="password" placeholder="Enter your Password here" class="input-fields">
        </div>
        
        <div class="mar">
            <button type="submit" class="action-buttons addquery" style="margin: 0;">Login</button>
        </div>    
    </form>
    <p>{{ invalid_login_msg }}</p>

    <p>Don't have an account?<a href="{% url 'accounts:register' %}">Register here</a></p>
</div>
{% endblock %}

templates/postquery.html
{% extends "base.html" %}

{% block content %}
<div class="head-container">
    <h1>Welocome to Post Queries Page</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="mar">
            {{ form.query }}
        </div>
        <div class="mar">
            {{ form.tag }}
        </div>
        <button type="submit" class="action-buttons addquery" style="margin: 0;">Submit</button>
    </form>
</div>
    
{% endblock %}

templates/posts.html
{% extends "base.html" %}

{% block content %}
    <!-- <div class="head-container">
        <h1>Welocome to Posts Page</h1>
    </div> -->
    <button class="action-buttons addquery" style="margin: 3rem;"><a href="./uploadpost">New Post</a></button>    
    <div class="post-container" style="margin: 2rem;">
    {% for content in contents reversed %}
            {% if content.author != user.username %}
                <div class="data-card bk">
                    <img src="./media/{{ content.postimage }}" alt="post" width="200">
                    <p><b>@{{ content.author }}</b></p>
                    <p>{{ content.caption }}</p>
                </div>
            {% endif %}
            <!-- {% if content.author == user.username %}
            <button><a href="{% url 'posts:editpost' content.id %}">Edit</a></button>
            <button><a href="{% url 'posts:deletepost' content.id %}">Delete</a></button>
            {% endif %} -->
    {% endfor %}

    </div>
    
{% endblock %}

templates/queries.html
{% extends "base.html" %}
{% block content %}
    <!-- <div class="head-container">
        <h1>Welocome to Queries Page</h1>
    </div>
     -->
    <form method="GET" class="forms">
        <input type="text" name="search-area" value="{{ search_input }}" class="input-fields">
        <button class="action-buttons search" type="submit">Search</button>
    </form>
    <br>
    
    <form method="GET" class="forms">
        <select name="filter_tags" id="filter_tags" class="input-fields">
            {% if tag_input %}
            <option value="{{ tag_input }}">{{ tag_input }}</option>
            {% endif %}
            <option value="">All</option>
            {% for tag in taglist %}
            <option value="{{ tag }}">{{ tag }}</option>
            {% endfor %}
        </select>
        <button class="action-buttons filter" type="submit">Filter</button>
    </form>

    <br>
    <button class="action-buttons addquery"><a href="./postquery">Post New Query</a></button>    
    <br>
    <div class="post-container">
        {% for content in contents reversed %}
            {% if content.author != user.username %}
                <div class="data-card bk">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <h3>{{ content.query }}</h3>
                        <p>by @{{ content.author }}</p>
                        <p>#{{ content.tag }}</p>
                    </div>
                    <button class="action-buttons read"><a href="{% url 'readanswers' content.id %}">Read Answers</a></button>
                </div>
                
            {% endif %}
        {% endfor %}
    </div>
    
{% endblock %}

templates/readblogs.html
{% extends "base.html" %}

{% block content %}
<div class="head-container">
    <div class="modal-dialog modal-dialog-scrollable data-card bk">
        <h3>{{ content.blogtopic }}</h3>
        <p><b>@{{ content.author }}</b></p>
        <p>#{{ content.tag }}</p>
        <p>{{ content.blogcontent }}</p>
    </div>
    <div class="data-card bk">
        <h3>Comments</h3>
        <form method="POST" class="mar">
            {% csrf_token %}
            <div>
                {{ form.commentcontent }}
            </div>
            <input type="submit" value="Submit">
        </form>
        {% if not content.comments.all %}
            <p>No Comments</p>
        {% else %}
            {% for comment in content.comments.all %}
                <div class="comment">
                    <p><strong>@{{ comment.commentauthor }}</strong> - {{ comment.commentcontent }}</p>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    
</div>

{% endblock %}

templates/uploadevent.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="head-container">
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="mar">
            {{ form.eventImg }}
        </div>
        <div class="mar">
            <label>Event Topic</label><br>
            {{ form.eventTopic }}
        </div>
        <div class="mar">
            <label>Date</label><br>
            {{ form.eventDate }}
        </div>
        <div class="mar">
            <label>Organized by</label><br>
            {{ form.eventOrganizer }}
        </div>
        <div class="mar">
            <label>Decsription</label><br>
            {{ form.eventDesc }}
        </div>
        <button type="submit" class="action-buttons addquery" style="margin: 0;">Submit</button>
    </form>
</div>

{% endblock %}

templates/viewprofile.html
{% extends "base.html" %}

{% block link %}
<style>
    .content-container{
    display: flex;
    justify-content: center;
}
</style>
{% endblock %}

{% block content %}
<div class="profile-container">
    <div class="card w-50" style="width: 18rem;">
        {% if userprofile.profile_pic %}
            <img src="../../media/{{ userprofile.profile_pic }}" class="card-img-top" alt="...">
        {% else %}
            <img class="profile-pic" src="../media/profile_pics/user.jpg" class="card-img-top" alt="...">
        {% endif %}
        
        <div class="card-body user-card">
          <h5 class="card-title user-info">{{ userprofile.user }}</h5>
          <p class="card-text user-info">{{ userprofile.user.first_name }} {{ userprofile.user.last_name }}</p>
          <p class="card-text user-info">{{ userprofile.user.email }}</p>
          <p class="card-text user-info">{{ userprofile.passed_out_year }}</p>
          <p class="card-text user-info">{{ userprofile.dept }}</p>
        </div>
    </div>

    <div class="user-content">
        {% if blogs %}
            <div class="blogs-container secondary-containers">
                <h3 class="headers algin-self">Blogs</h3>
                {% for blog in blogs %}
                    {% if blog.author == userprofile.user.username %}
                        <div class="data-card">    
                            <h3><a href="{% url 'readblogs' blog.id %}">{{ blog.blogtopic }}</a></h3>
                            <p>{{ blog.tag }}</p>
                            <div class="flex">
                                <!-- <button class="action-buttons pri"><a href="{% url 'editblogs' blog.id %}">Edit Blog</a></button>
                                <button class="action-buttons del"><a href="{% url 'deleteblogs' blog.id %}">Delete Blog</a></button> -->
                            </div>
                            
                        </div>
                    {% endif %}                    
                {% endfor %}
            </div>
        {% endif %}
        {% if posts %}
            <div class="posts-conatiner secondary-containers">
                <h3 class="headers algin-self">Posts</h3>
                {% for post in posts %}
                    {% if post.author == userprofile.user.username %}
                        <div class="data-card">
                            {% block postimage %}
                                <img src="../../media/{{ post.postimage }}" alt="post" width="200">
                            {% endblock %}
                            <p>{{ post.caption }}</p>
                            <div class="flex">
                                <!-- <button class="action-buttons pri"><a href="{% url 'posts:editpost' post.id %}">Edit</a></button>
                                <button class="action-buttons del"><a href="{% url 'posts:deletepost' post.id %}">Delete</a></button> -->
                            </div>
                            
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        {% if contents %}
            <div class="queries-container secondary-containers">
                <h3 class="headers algin-self">Queries</h3>
                {% for content in contents %}
                    {% if content.author == userprofile.user.username %}
                    <div class="data-card">
                        <p>{{ content.query }}</p>
                        <p>{{ content.tag }}</p>
                        <button class="action-buttons read"><a href="{% url 'readanswers' content.id %}">Read Answers</a></button>
                        <!-- <button class="action-buttons del"><a href="{% url 'deletequery' content.id %}">Delete Query</a></button> -->
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}